"""The swingtag backlog as data: epics > stories > tasks and experiments.

Source of truth for the GitHub issues and the GitHub Project board; the issues
are created from this file by `plans/create_backlog.py`. Each entry:

    key       stable identifier, used for parent and dependency links
    level     epic | story | task | experiment
    title     issue title
    parent    key of the parent (stories -> epic, tasks -> story)
    area      core | theme | publisher | infra | examples | tooling | docs | process
    priority  must | should | could
    spec      references into spec/SPEC.md and spec/ASSUMPTIONS.md
    what      what to do (tasks) or the user value (epics, stories)
    done      acceptance criteria, each one verifiable
    deps      keys this item is blocked by
    closed    True when already done (kept for traceability)
    reason    completed | not_planned, the close reason on GitHub
"""

E, S, T, X = "epic", "story", "task", "experiment"


def item(key, level, title, parent=None, area="process", priority="must", spec="",
         what="", done=(), deps=(), closed=False, reason="completed"):
    return dict(key=key, level=level, title=title, parent=parent, area=area,
                priority=priority, spec=spec, what=what, done=list(done),
                deps=list(deps), closed=closed, reason=reason)


BACKLOG = [
    # ------------------------------------------------------------------ E1
    item("E1", E, "Specification and assumption validation", area="process",
         what="Phases 1-5 of spec-driven development: spikes, reference, spec, test plan, "
              "implementation plan, and the empirical confirmation of every technical "
              "assumption before implementation relies on it.",
         done=["spec/SPEC.md approved", "every assumption in spec/ASSUMPTIONS.md CONFIRMED or "
               "scheduled in the release verification story", "TEST-PLAN.md and plans/ approved"]),

    item("S1.1", S, "Spikes and local experiments", "E1",
         what="As a contributor, I want the unknowns answered by throwaway code before the spec "
              "is written on top of them.",
         done=["spikes promoted to spec/spikes/reference with PROVES/SHORTCUT markers",
               "local assumptions T-01..T-23 have an experiment and a status"], closed=True),
    item("spike-s1", X, "S1: delivery CSP vs direct audio/video", "S1.1", spec="T-11, 10.7",
         what="Serve media with the inherited CSP and open them in Chrome.",
         done=["default-src 'none' without media-src blocks .mp4 (observed)",
               "media-src 'self' fixes .mp4 and .m4a (observed)"], closed=True),
    item("spike-s2", X, "S2: .url and .webloc parsing with the standard library", "S1.1",
         spec="T-06, FR-8", done=["11/11 cases pass in spikes/reference/link-parsing"], closed=True),
    item("spike-s3", X, "S3: theme validation and unicode fileset in Terraform", "S1.1",
         spec="T-07, T-08", done=["preconditions stop plan with readable messages",
                                  "fileset returns NFC paths"], closed=True),
    item("exp-local", X, "Local experiments T-01..T-23", "S1.1", spec="spec/ASSUMPTIONS.md",
         what="e_core.py, e_page.py, e_serve.py, e_qr_decode.py, e_terraform/.",
         done=["results recorded in ASSUMPTIONS.md",
               "refuted assumptions (T-05, T-11, T-14, T-22) fixed in SPEC 0.2"], closed=True),

    item("S1.2", S, "Approved specification, test plan and implementation plan", "E1",
         what="As a contributor, I want every decision taken before code, so that "
              "implementation cannot diverge.",
         done=["SPEC.md, TEST-PLAN.md and plans/ approved by the owner"]),
    item("spec-draft", T, "Write SPEC.md (glossary, actors, stories, FR, edge cases, technical spec)",
         "S1.2", spec="spec/SPEC.md", done=["v0.2 committed"], closed=True),
    item("assumptions-register", T, "Create the technical assumptions register", "S1.2",
         spec="spec/ASSUMPTIONS.md", done=["every technical assumption listed with experiment and status"],
         closed=True),
    item("spec-review", T, "Owner review of SPEC 0.2 and decision on the license (Q-1)", "S1.2",
         spec="SPEC 14", what="License (recommended MIT). Q-2 resolved: name swingtag. Q-3 resolved: no permission needed.",
         done=["review comments applied", "Q-1 answered in SPEC 14", "SPEC status: approved"]),
    item("test-plan", T, "Write spec/TEST-PLAN.md (phase 4)", "S1.2", spec="spec/README.md phase 4",
         what="Every test with name, input, expected output; unit, Terraform, live and device "
              "levels; mapped to FR/EC/US.",
         done=["every FR and EC is covered by at least one named test", "no test uses vague "
               "wording (no 'gracefully', 'correctly')", "owner approval"],
         deps=["spec-review"]),
    item("impl-plan", T, "Write the implementation plan in plans/ (phase 5)", "S1.2",
         spec="spec/README.md phase 5",
         what="File by file, function by function, referencing the backlog task keys.",
         done=["no architectural decision appears in the plan that is not in the spec",
               "owner approval"], deps=["test-plan"]),
    item("repo-claude-md", T, "Add CLAUDE.md with the SDD rules for agents working on the repo",
         "S1.2", spec="spec/README.md",
         done=["red flag rule, ambiguity rule, assumptions rule and backlog workflow stated",
               "points to SPEC, ASSUMPTIONS, TEST-PLAN, plans/"]),

    item("S1.3", S, "Experiment environment on AWS", "E1",
         what="As a contributor, I want a disposable AWS stack to run the experiments that "
              "cannot run locally.",
         done=["an account and a budget alarm exist", "a minimal stack deploys and destroys cleanly"]),
    item("aws-account", T, "Choose the AWS account for experiments",
         "S1.3", what="Decided 2026-09-25: experiments run on the owner's existing lab account; the "
                      "CLI profile lives in the owner's local configuration, never in the repository. "
                      "Every experiment resource is tagged project=swingtag and destroyed after use.",
         done=["account decided", "tagging and destroy-after-use rule stated"], closed=True),
    item("aws-harness", T, "Experiment harness: minimal Terraform stack in spec/experiments/aws/",
         "S1.3", area="infra",
         what="Bucket (versioned, SSE-S3), SQS queue + DLQ, stub Lambda (python3.12 arm64) wired "
              "through an event source mapping, CloudFront with OAC on public/, a rewrite "
              "function slot. Parameterised so that each experiment adds only what it tests.",
         done=["terraform apply and destroy succeed from a clean state", "README with usage"],
         deps=["aws-account"]),

    item("S1.4", S, "Validate the AWS assumptions", "E1",
         what="As a contributor, I want every AWS-dependent assumption confirmed on real "
              "infrastructure before implementation relies on it.",
         done=["T-30..T-49 and T-54 PENDING-AWS entries turned CONFIRMED or REFUTED -> FIXED in "
               "ASSUMPTIONS.md with command and evidence"]),
] + [
    item(f"exp-{tid.lower()}", X, f"{tid}: {title}", "S1.4", area="infra", spec=f"{tid}, {ref}",
         what=how, done=[f"ASSUMPTIONS.md {tid} updated with the command run and the observed "
                         f"result", "experiment code committed under spec/experiments/aws/"],
         deps=["aws-harness"])
    for tid, title, ref, how in [
        ("T-30", "macOS-built package imports qrcode on Lambda python3.12 arm64", "A-6",
         "Build with build_lambda.sh, deploy the stub, invoke a handler that renders an SVG QR."),
        ("T-31", "Lambda python3.12 runtime has the tz database", "FR-27",
         "Invoke ZoneInfo('Europe/Rome') and an invalid zone; record outputs."),
        ("T-32", "ETag equals MD5 and survives CopyObject with MetadataDirective=REPLACE", "10.6",
         "Upload single-part objects (pdf, mp4), copy with new Content-Type and Disposition, "
         "compare ETags and local MD5."),
        ("T-34", "Writes under public/ and config/ produce no queue messages", "EC-27",
         "Write objects under both prefixes, poll the queue and the Lambda logs for 2 minutes."),
        ("T-37", "Upload-to-page latency is at most 60 s", "FR-20..22",
         "Upload, timestamp the Lambda start and the public object LastModified, 10 samples; "
         "report p50 and max."),
        ("T-38", "CloudFront cannot reach source/ or config/", "10.7",
         "Request /../source/x, /source/x, /config/theme.json and encoded variants; expect 404 page."),
        ("T-40", "Rewrite function behaves as tabled, /_assets untouched", "10.7, EC-33",
         "aws cloudfront test-function for /, /tok, /tok/, /tok/a/b.pdf, /_assets/logo.svg."),
        ("T-41", "Headers policy (CSP with media-src) applies to pages, media and errors", "10.7",
         "curl -I on index, mp4, 404; compare header sets."),
        ("T-42", "CloudFront answers 206 with Accept-Ranges on mp4 range requests", "FR-47",
         "curl -r 0-99 on an mp4 through the distribution, cold and cached."),
        ("T-44", "aws_lambda_invocation runs at create and only on trigger change", "FR-15",
         "Apply three times: unchanged, changed fingerprint, changed package; count invocations."),
        ("T-45", "Uploads with depends_on all produce notifications", "FR-41",
         "Apply bucket+notification+50 objects in one run; count messages received."),
        ("T-46", "Default certificate works; alias provider passed with zero ACM resources", "FR-44",
         "Apply the module with domain_name empty; curl https on the cloudfront domain."),
        ("T-47", "force_destroy removes a versioned bucket with noncurrent versions", "FR-42",
         "Create versions and delete markers, terraform destroy, confirm bucket gone."),
        ("T-48", "Delimiter listing on ' · ' names and synthetic SQS bodies work", "10.5",
         "List item prefixes under source/, send synthetic messages, observe stub handler parsing."),
        ("T-49", "ListBucket with s3:prefix conditions allows the publisher's listings", "10.8",
         "Role with the spec policy lists source/ and public/ with delimiter, is denied config/."),
        ("T-54", "A message in the DLQ raises the CloudWatch alarm", "FR-26",
         "Force a failing handler 5 times, observe ALARM state."),
    ]
] + [
    item("S1.5", S, "Validate the device assumptions", "E1",
         what="As a visitor, I want the page and media to work on the phones people actually use.",
         done=["T-60..T-63 CONFIRMED in ASSUMPTIONS.md with device, OS version and screenshots"]),
] + [
    item(f"exp-{tid.lower()}", X, f"{tid}: {title}", "S1.5", area="theme", spec=tid, what=how,
         done=[f"ASSUMPTIONS.md {tid} updated with device, OS and browser versions and a screenshot"],
         deps=deps)
    for tid, title, how, deps in [
        ("T-60", "iOS Safari plays m4a and mp4 opened directly under the CSP",
         "Open the harness media URLs on an iPhone; play to the end; seek.", ["exp-t-41", "exp-t-42"]),
        ("T-61", "iOS Safari renders color-mix and the page layout",
         "Open the prototype page (e_page.py output) served by the harness.", ["aws-harness"]),
        ("T-62", "Android Chrome opens pdf, image, audio and video from the page",
         "Tap each kind on an Android phone; record whether inline or system viewer.", ["exp-t-41"]),
        ("T-63", "Plates-sheet QR scans at arm's length",
         "Print the plates sheet at 100%, scan each code with the default camera app.", ["plates"]),
    ]
] + [
    # ------------------------------------------------------------------ E2
    item("E2", E, "Content convention and catalogue (pure core)", area="core",
         what="The naming rules and the item model, as pure functions testable without AWS.",
         done=["convention.py, formats.py, catalog.py implemented per SPEC 10.3", "unit tests green"]),
    item("S2.0", S, "Project scaffolding and CI", "E2", area="core",
         what="As a contributor, I want a runnable test suite and CI from the first commit.",
         done=["pytest runs locally and in GitHub Actions", "terraform fmt/validate in CI"]),
    item("scaffold", T, "pyproject, src layout, pytest config, Makefile test target", "S2.0",
         area="core", spec="10.2, 10.10",
         done=["make test runs an empty suite green", "src/swingtag importable in tests"],
         deps=["impl-plan"]),
    item("ci", T, "GitHub Actions: pytest, terraform fmt -check and validate", "S2.0", area="core",
         done=["workflow green on main", "fails on a formatting error (verified once)"],
         deps=["scaffold"]),
    item("S2.1", S, "Labels and order come from folder names (US-5)", "E2", area="core",
         spec="US-5, FR-4..FR-6",
         what="As an owner, I want button labels and order to come from names.",
         done=["all tasks closed", "FR-4..FR-6 tests green"]),
    item("core-names", T, "convention.py: normalize, parse_order, sort_key, is_ignored", "S2.1",
         area="core", spec="FR-5, FR-6, FR-9, T-01, T-04",
         done=["tests for the four order separators, digits-only names, NFC merge, ignored names"],
         deps=["scaffold"]),
    item("core-tokens", T, "convention.py: tokens (is_token, token_for, split_item_name, with_token)",
         "S2.1", area="core", spec="FR-2, FR-3, FR-10, T-02, T-03",
         done=["tests: alphabet and length, determinism, key sensitivity, last-separator rule, "
               "invalid tail is part of the label"], deps=["scaffold"]),
    item("core-slugs", T, "convention.py: slug and unique_slug with transliteration table", "S2.1",
         area="core", spec="FR-38, EC-9, EC-10, T-05",
         done=["tests: Straße -> strasse, Œuvre -> oeuvre, ★★★ -> fallback, collision suffixes"],
         deps=["scaffold"]),
    item("S2.2", S, "PDF, images, audio, video and links are accepted (US-6)", "E2", area="core",
         spec="US-6, FR-7, FR-8", what="As an owner, I want each object to get the right medium.",
         done=["all tasks closed"]),
    item("core-formats", T, "formats.py: FORMATS table and lookup()", "S2.2", area="core",
         spec="FR-7, EC-16", done=["tests for every extension, case-insensitivity, unknown -> None"],
         deps=["scaffold"]),
    item("core-links", T, "formats.py: parse_link() from the S2 reference", "S2.2", area="core",
         spec="FR-8, EC-12..EC-14, T-06",
         done=["the 11 spike cases as unit tests", "64 KiB cap test"], deps=["scaffold"]),
    item("S2.3", S, "A folder becomes an item model (US-4, US-9)", "E2", area="core",
         spec="US-4, US-9, FR-1, FR-9",
         what="As an owner, I want my folders turned into a menu, mistakes ignored.",
         done=["all tasks closed"]),
    item("core-catalog-model", T, "catalog.py: dataclasses, item_prefix, split_prefix", "S2.3",
         area="core", spec="10.3", done=["tests for depth rules and prefix extraction"],
         deps=["core-tokens"]),
    item("core-catalog-build", T, "catalog.py: build_item grouping, labels, order, anomalies", "S2.3",
         area="core", spec="FR-4, FR-9, EC-8, EC-9, EC-11, EC-15..EC-17",
         done=["tests per row of the FR-9 table", "one-vs-many resources labelling"],
         deps=["core-catalog-model", "core-names", "core-slugs", "core-formats"]),
    item("core-catalog-links", T, "catalog.py: link entries, published_keys, updated_at", "S2.3",
         area="core", spec="FR-8, FR-27, EC-18",
         done=["links excluded from published_keys", "updated_at = max modified incl. links",
               "item with only invalid links is empty"],
         deps=["core-catalog-build", "core-links"]),

    # ------------------------------------------------------------------ E3
    item("E3", E, "Theme, wording and page", area="theme",
         what="Themed, localised, fast mobile pages and QR codes.",
         done=["theme.py, i18n.py, render.py, qr.py implemented", "unit tests green"]),
    item("S3.1", S, "Operator brands the pages with one file (US-15)", "E3", area="theme",
         spec="US-15, FR-12..FR-14", done=["all tasks closed"]),
    item("theme-model", T, "theme.py: Theme and Colors, defaults, tolerant from_json", "S3.1",
         area="theme", spec="FR-12, FR-15, EC-20, EC-21",
         done=["missing theme -> DEFAULT_THEME", "bad values fall back and are logged",
               "invalid timezone -> UTC"], deps=["scaffold"]),
    item("theme-i18n", T, "i18n.py: STRINGS en/it and format_date", "S3.1", area="theme",
         spec="FR-14, FR-33, T-17",
         done=["every FR-14 key in both locales", "date formats per locale", "override via strings"],
         deps=["scaffold"]),
    item("S3.2", S, "Visitor gets a fast, readable page (US-11..US-14)", "E3", area="theme",
         spec="US-11..US-14, FR-30..FR-37", done=["all tasks closed"]),
    item("page-style", T, "render.py: CSS with derived tones and the five kind icons", "S3.2",
         area="theme", spec="FR-31, T-14, T-16",
         done=["secondary tones only from text/background/primary", "dark block only when "
               "colors_dark or default theme", "icons carry kind_* accessible names"],
         deps=["theme-model"]),
    item("page-render", T, "render.py: render_page structure, escaping, links", "S3.2", area="theme",
         spec="FR-30..FR-34, T-15",
         done=["tests: no <script>, one <style>, < 15 KB with 10 buttons, absolute file links, "
               "link buttons with rel=noopener noreferrer, subtitle rule, escaping of names"],
         deps=["page-style", "theme-i18n", "core-catalog-links"]),
    item("page-404", T, "render.py: render_not_found", "S3.2", area="theme", spec="FR-35",
         done=["themed, localised, reveals nothing about tokens"], deps=["page-style", "theme-i18n"]),
    item("page-qr", T, "qr.py: qr_svg at level Q", "S3.2", area="theme", spec="FR-37, T-12, T-13",
         done=["test decodes the generated SVG back to the URL (dev dependency)"], deps=["scaffold"]),

    # ------------------------------------------------------------------ E4
    item("E4", E, "Publisher", area="publisher",
         what="The Lambda function that compiles the source zone into the public zone.",
         done=["publish.py, handler.py, settings.py implemented", "tests with stubbed AWS clients green"]),
    item("S4.1", S, "A new folder is published and christened (US-4)", "E4", area="publisher",
         spec="US-4, FR-10, FR-20", done=["all tasks closed"]),
    item("pub-settings", T, "settings.py: Settings.from_env", "S4.1", area="publisher", spec="10.4",
         done=["required variables fail fast with the variable name", "prefix normalisation"],
         deps=["scaffold"]),
    item("pub-listing", T, "publish.py: paginated listing and common prefixes", "S4.1",
         area="publisher", spec="10.6 step 1, EC-35",
         done=["tests with a stub client returning 3 pages"], deps=["pub-settings"]),
    item("pub-christen", T, "publish.py: christening (copy to tokenised prefix, delete, relist)",
         "S4.1", area="publisher", spec="FR-10, 10.6 step 3, EC-2, EC-3",
         done=["empty folder never christened", "same token from two runs"],
         deps=["pub-listing", "core-tokens"]),
    item("pub-theme", T, "publish.py: load theme.json once per invocation with fallback", "S4.1",
         area="publisher", spec="FR-15, EC-20", done=["missing/invalid object -> default theme, logged"],
         deps=["theme-model", "pub-settings"]),
    item("S4.2", S, "Replacing and removing files is reflected idempotently (US-7)", "E4",
         area="publisher", spec="US-7, FR-21..FR-23", done=["all tasks closed"]),
    item("pub-copy", T, "publish.py: copy resources with type, disposition, cache, ETag skip, 5 GiB cap",
         "S4.2", area="publisher", spec="10.6 step 7, FR-36, EC-15, T-32",
         done=["MetadataDirective REPLACE with FR-7 type", "ASCII filename fallback",
               "equal ETag -> no copy", "> 5 GiB -> anomaly"],
         deps=["pub-listing", "core-catalog-links", "exp-t-32"]),
    item("pub-write", T, "publish.py: write index.html and qr.svg only when changed", "S4.2",
         area="publisher", spec="10.6 steps 8-9, FR-23",
         done=["second publish of unchanged item writes nothing"],
         deps=["page-render", "page-qr", "pub-theme"]),
    item("pub-prune", T, "publish.py: conservative prune and non-blocking invalidation", "S4.2",
         area="publisher", spec="10.6 steps 10-11, EC-26, EC-28",
         done=["objects newer than run start are spared", "invalidation error logged, not raised"],
         deps=["pub-listing"]),
    item("S4.3", S, "Renaming, moving and emptying keep codes working (US-8)", "E4",
         area="publisher", spec="US-8, FR-24, FR-25", done=["all tasks closed"]),
    item("pub-empty", T, "publish.py: empty-prefix branch with token owner search", "S4.3",
         area="publisher", spec="10.6 step 2, EC-4, EC-5, EC-34",
         done=["rename keeps publication", "move across collections keeps publication",
               "emptied item removed"], deps=["pub-listing", "pub-prune"]),
    item("pub-duplicate", T, "publish.py: duplicate token detection", "S4.3", area="publisher",
         spec="10.6 step 4, EC-7", done=["lexically smaller prefix wins", "other logged, not published"],
         deps=["pub-listing"]),
    item("S4.4", S, "Theme changes reach every page (US-16)", "E4", area="publisher",
         spec="US-16, FR-15", done=["all tasks closed"]),
    item("pub-error-page", T, "publish.py: publish_error_page", "S4.4", area="publisher",
         spec="FR-35", done=["writes public/404.html with the theme"], deps=["page-404", "pub-theme"]),
    item("pub-republish", T, "publish.py: republish_all enqueues one message per item", "S4.4",
         area="publisher", spec="10.5, T-48",
         done=["batches of 10", "returns the count", "invalidates /404.html and /_assets/*"],
         deps=["pub-listing", "exp-t-48"]),
    item("S4.5", S, "Failures surface and never block other items (US-20)", "E4", area="publisher",
         spec="US-20, FR-26", done=["all tasks closed"]),
    item("pub-handler-sqs", T, "handler.py: SQS batch parsing, grouping, batchItemFailures", "S4.5",
         area="publisher", spec="10.5, EC-1, EC-23..EC-25",
         done=["unquote_plus on keys", "TestEvent and garbage skipped", "only failed ids returned"],
         deps=["core-catalog-model"]),
    item("pub-handler-direct", T, "handler.py: direct republish_all action and logging setup", "S4.5",
         area="publisher", spec="10.5, trap 'logging.basicConfig'",
         done=["action dispatch tested", "root logger level set when handlers exist"],
         deps=["pub-handler-sqs", "pub-republish", "pub-error-page"]),

    # ------------------------------------------------------------------ E5
    item("E5", E, "Infrastructure module (terraform/)", area="infra",
         what="The reusable Terraform module described in SPEC 10.7-10.9.",
         done=["module applies from an example", "terraform validate green"]),
    item("S5.1", S, "Storage and eventing", "E5", area="infra", done=["all tasks closed"]),
    item("infra-s3", T, "s3.tf: bucket, SSE, versioning, lifecycle, public block, TLS deny, notifications",
         "S5.1", area="infra", spec="10.8, EC-27", done=["notifications filtered on source/"],
         deps=["infra-interface"]),
    item("infra-sqs", T, "sqs.tf: publish queue, dead-letter queue, alarm", "S5.1", area="infra",
         spec="10.13, FR-26, T-54", done=["visibility 6x timeout", "maxReceiveCount 5", "alarm on DLQ"],
         deps=["infra-interface"]),
    item("S5.2", S, "Compute", "E5", area="infra", done=["all tasks closed"]),
    item("infra-lambda", T, "lambda.tf: function, least-privilege role, event source mapping, logs, secret",
         "S5.2", area="infra", spec="10.4, 10.8, 10.13, T-35, T-49",
         done=["maximum_concurrency 2, ReportBatchItemFailures, no reserved concurrency",
               "token secret with ignore_changes", "no wildcard resources"],
         deps=["infra-interface", "build-lambda", "exp-t-49"]),
    item("build-lambda", T, "scripts/build_lambda.sh", "S5.2", area="infra", spec="A-6, T-30",
         done=["build/lambda contains swingtag and qrcode 8.2 only"], deps=["scaffold", "exp-t-30"]),
    item("S5.3", S, "Delivery (US-11, US-14, US-18)", "E5", area="infra", done=["all tasks closed"]),
    item("infra-cloudfront", T, "cloudfront.tf: distribution, OAC, error responses, headers policy",
         "S5.3", area="infra", spec="10.7, T-38, T-39, T-41, T-42",
         done=["403 and 404 -> /404.html 404", "CSP includes media-src 'self'"],
         deps=["infra-interface", "exp-t-41"]),
    item("infra-rewrite", T, "functions/rewrite.js with a local test table", "S5.3", area="infra",
         spec="10.7, EC-33, T-40", done=["node test for every row of the rewrite table"],
         deps=["exp-t-40"]),
    item("infra-dns", T, "dns.tf: conditional ACM (us-east-1) and alias records", "S5.3",
         area="infra", spec="FR-44, EC-32, T-21, T-46",
         done=["count = 0 without domain", "plan fails with the message when zone is missing"],
         deps=["infra-interface", "exp-t-46"]),
    item("S5.4", S, "Theme pipeline (US-15..US-17)", "E5", area="infra", done=["all tasks closed"]),
    item("infra-theme-validate", T, "theme.tf: validation preconditions and contrast checks", "S5.4",
         area="infra", spec="FR-12, FR-13, FR-31, T-07, T-09, T-10, T-19",
         done=["one precondition per FR-12 rule", "contrast warnings via check blocks"],
         deps=["infra-interface"]),
    item("infra-theme-publish", T, "theme.tf: theme.json and assets upload, fingerprint, invocation",
         "S5.4", area="infra", spec="FR-15, T-20, T-44",
         done=["republish-all runs once per theme or package change"],
         deps=["infra-theme-validate", "infra-lambda", "exp-t-44"]),
    item("S5.5", S, "Module interface and access (US-19)", "E5", area="infra",
         done=["all tasks closed"]),
    item("infra-interface", T, "versions.tf, variables.tf, outputs.tf per SPEC 10.9", "S5.5",
         area="infra", spec="10.9", done=["terraform validate on the empty module"],
         deps=["impl-plan"]),
    item("infra-uploaders", T, "Uploader principals limited to source/", "S5.5", area="infra",
         spec="FR-46, T-50", done=["policy statement only when the list is non-empty"],
         deps=["infra-s3"]),

    # ------------------------------------------------------------------ E6
    item("E6", E, "Examples and one-command demo", area="examples",
         what="Three fictional deployments that show the idea in one command.",
         done=["make demo works for the three examples", "pages output lists every item"]),
    item("S6.1", S, "One command deploys and removes an example (US-2, US-3)", "E6",
         area="examples", spec="US-2, US-3, FR-40..FR-43", done=["all tasks closed"]),
    item("make-demo", T, "Makefile: demo, plan, destroy, fmt with EXAMPLE", "S6.1", area="examples",
         spec="10.10", done=["EXAMPLE defaults to restaurant", "demo runs test and build first"],
         deps=["scaffold"]),
    item("examples-main", T, "examples/<name>/main.tf pattern with content upload and outputs",
         "S6.1", area="examples", spec="10.9, FR-41, FR-43, T-45, T-47",
         done=["pages and qr_codes outputs computed from folder names", "force_destroy true",
               "republish-all after uploads"],
         deps=["infra-theme-publish", "infra-cloudfront", "infra-s3", "exp-t-45"]),
    item("examples-token-test", T, "Unit test: every example item folder carries a valid token",
         "S6.1", area="examples", spec="FR-43, US-23, trap 'example folders without token'",
         done=["fails on a folder without token (verified once)"], deps=["core-tokens"]),
    item("S6.2", S, "Placeholder media", "E6", area="examples", spec="10.11, T-23",
         what="Produced once outside the repository and committed as static files.",
         done=["all files under 100 KB"]),
    item("media-pdf", T, "Placeholder PDFs for the three examples", "S6.2", area="examples",
         done=["1-2 pages each, readable titles, under 100 KB"]),
    item("media-jpg", T, "Placeholder JPEGs for the nursery plants", "S6.2", area="examples",
         done=["six images under 100 KB"]),
    item("media-audio", T, "Placeholder M4A guides for the exhibition works", "S6.2", area="examples",
         done=["six files under 100 KB, AAC, English voice"]),
    item("media-video", T, "Placeholder MP4 clips (nursery pruning, exhibition works)", "S6.2",
         area="examples", done=["H.264 +faststart, 720x1280, under 100 KB each"]),
    item("S6.3", S, "Restaurant example: Osteria Quattro Mestoli", "E6", area="examples",
         spec="10.11", done=["all tasks closed"]),
    item("ex-restaurant-theme", T, "Restaurant theme.yaml and monogram logo SVG", "S6.3",
         area="examples", spec="10.11, T-22", done=["no contrast warning at plan"]),
    item("ex-restaurant-content", T, "Restaurant content tree (Menu item, 5 entries)", "S6.3",
         area="examples", spec="10.11", done=["tokenised folder names", "prenota.url valid"],
         deps=["media-pdf"]),
    item("S6.4", S, "Nursery example: Vivaio Radici Lente", "E6", area="examples", spec="10.11",
         done=["all tasks closed"]),
    item("ex-nursery-theme", T, "Nursery theme.yaml and leaf logo SVG", "S6.4", area="examples",
         done=["no contrast warning at plan"]),
    item("ex-nursery-content", T, "Nursery content tree (6 plants, 5 entries each)", "S6.4",
         area="examples", done=["tokenised folder names", "pdf, jpg, mp4, url per plant"],
         deps=["media-pdf", "media-jpg", "media-video"]),
    item("S6.5", S, "Exhibition example: Tides of Light", "E6", area="examples", spec="10.11",
         done=["all tasks closed"]),
    item("ex-exhibition-theme", T, "Exhibition theme.yaml (en) and frame logo SVG", "S6.5",
         area="examples", done=["primary #8c6d0f, no contrast warning at plan"]),
    item("ex-exhibition-content", T, "Exhibition content tree (6 works, 5 entries each)", "S6.5",
         area="examples", done=["tokenised folder names", "pdf, m4a, mp4, webloc per work"],
         deps=["media-pdf", "media-audio", "media-video"]),

    # ------------------------------------------------------------------ E7
    item("E7", E, "Operator tooling", area="tooling", priority="should",
         what="Printable plates and live verification.", done=["make plates and make verify work"]),
    item("S7.1", S, "Printable sheet of all QR codes (US-10)", "E7", area="tooling",
         priority="should", spec="US-10, FR-45", done=["all tasks closed"]),
    item("pdfmin", T, "scripts/pdfmin.py minimal PDF writer", "S7.1", area="tooling",
         priority="should", done=["unit test: output opens in a PDF reader (header, xref valid)"],
         deps=["scaffold"]),
    item("plates", T, "scripts/plates.py and make plates", "S7.1", area="tooling", priority="should",
         spec="FR-45, T-63", done=["A4 3x6 grid from the source listing", "only christened items"],
         deps=["pdfmin", "core-tokens"]),
    item("S7.2", S, "Live verification of a deployment (US-21)", "E7", area="tooling",
         priority="should", spec="US-21, FR-47", done=["all tasks closed"]),
    item("verify", T, "scripts/verify.sh and make verify", "S7.2", area="tooling",
         priority="should", spec="FR-47, T-41, T-42",
         done=["every FR-47 check implemented", "exit code = failed checks", "bash 3.2 safe"],
         deps=["examples-main"]),

    # ------------------------------------------------------------------ E8
    item("E8", E, "Documentation and release", area="docs",
         what="README, release verification on real infrastructure, going public.",
         done=["README published", "all ORIGIN assumptions re-run", "repository public"]),
    item("S8.1", S, "Stranger understands swingtag in a minute (US-1)", "E8", area="docs",
         spec="US-1, FR-50", done=["all tasks closed"]),
    item("readme", T, "README per FR-50", "S8.1", area="docs", spec="FR-50",
         done=["sections in the FR-50 order", "fictional disclaimer", "domain warning"],
         deps=["make-demo"]),
    item("screenshots", T, "Screenshots of the three examples from real deployments", "S8.1",
         area="docs", done=["docs/screenshots/*.png at phone width, light theme"],
         deps=["examples-main", "ex-restaurant-content", "ex-nursery-content",
               "ex-exhibition-content"]),
    item("license", T, "Add LICENSE", "S8.1", area="docs", spec="Q-1", deps=["spec-review"],
         done=["LICENSE file matches the chosen license"]),
    item("S8.2", S, "Release verification on swingtag infrastructure", "E8", area="docs",
         what="As the owner, I want every assumption observed only in the origin system "
              "re-run on swingtag before release.",
         done=["ORIGIN entries in ASSUMPTIONS.md turned CONFIRMED"]),
] + [
    item(f"rel-{tid.lower()}", X, f"Re-run {tid} on swingtag: {title}", "S8.2", area="docs",
         spec=tid, done=[f"ASSUMPTIONS.md {tid} CONFIRMED with command and evidence"],
         deps=["examples-main"])
    for tid, title in [
        ("T-33", "URL-encoded keys and TestEvent in S3 notifications"),
        ("T-35", "batch item failures and maximum concurrency"),
        ("T-36", "10-file upload yields one publication"),
        ("T-39", "403 and 404 surface as the themed 404"),
        ("T-43", "invalidation refreshes page and resources"),
        ("T-50", "uploader principals limited to source/"),
        ("T-51", "conservative pruning under overlapping runs"),
        ("T-52", "concurrent christening converges"),
        ("T-53", "rename and move keep the URL"),
        ("T-55", "make demo under 20 minutes on a fresh account"),
    ]
] + [
    item("S8.3", S, "Go public", "E8", area="docs",
         done=["repository public with a fresh, sanitised history"]),
    item("permission", T, "Obtain permission from the origin system's owner", "S8.3", area="docs",
         spec="Q-3", what="Not needed: owner decision of 2026-09-25. Closed as not planned.",
         done=["decision recorded in SPEC 14"], closed=True, reason="not_planned"),
    item("name-check", T, "Check the project name on GitHub, PyPI and npm", "S8.3",
         area="docs", spec="Q-2",
         what="Done 2026-09-25 with a positioning study: placard taken everywhere; swingtag has 0 "
              "GitHub repositories and is free on PyPI and npm. Repository and board renamed.",
         done=["decision recorded in SPEC 14", "repository and project renamed"], closed=True),
    item("sanitise", T, "Sanitisation check before publishing", "S8.3", area="docs",
         what="Run a denylist grep kept outside the repository over the tree and the full git "
              "history; review commit authors and emails.",
         done=["zero matches in tree and history", "author identity is the personal one"],
         deps=["readme"]),
    item("go-public", T, "Switch the repository to public", "S8.3", area="docs",
         done=["repository visibility public", "project board visibility decided"],
         what="Only when the owner decides to publish; the repository stays private until then.",
         deps=["name-check", "sanitise", "license", "screenshots"]),
]
